### ISSUE TITLE
Ciekawe geny

### ISSUE THREAD

**Issue by AleksandraDabrowska** [geneticsMiNIng/MLGenSig#49]
Znaleźć "ciekawe", zróżnicowane geny (genereg_vs_met)

np "ERBB2"

**Comment by agosiewska** [comment]
BRCA chr 17

Dużo sond:
BRCA1
CACNA1G
ERBB2
HOXB4
MRPL12

**Comment by AleksandraDabrowska** [comment]
Geny do sprawdzenia

https://www.biostars.org/p/77590/

PAM50
