### ISSUE TITLE
Wykres metylacja

### ISSUE THREAD

**Issue by agosiewska** [geneticsMiNIng/MLGenSig#5]
regiony genów vs metylacja
boxploty ekspresja w grupach

**Comment by AleksandraDabrowska** [comment]
przyjrzeć się "ciekawym" genom (zróżnicowana p wartość)

**Comment by agosiewska** [comment]
dodać lokalizacje sond na wykresie
pokolorować sondy z takimi samymi wartościami CpG_ISLAND_LOCATIONS (?)

**Comment by agosiewska** [comment]
#29  #25
