### ISSUE TITLE
Porównanie

### ISSUE THREAD

**Issue by AleksandraDabrowska** [geneticsMiNIng/MLGenSig#69]
Pdf generujący wykresy dla wybranych (~20) genów dla zbiorów danych `surv` dla BRCA i LUSC.

**Comment by agosiewska** [comment]
na początek jeden chromosom, żeby się szybciej liczyło?

**Comment by AleksandraDabrowska** [comment]
napisać funkcję generującą raport dla dowolnej liczby istotnych genów.

dodać opis do volcano plotów - jakie dane, jaki test

dodać p-wartości z testów na (nad) wykresach gene_reg_vs_met.
