### ISSUE TITLE
Nowe nazwy funkcji

### ISSUE THREAD

**Issue by agosiewska** [geneticsMiNIng/MLGenSig#75]
Zmiany w nazwach funkcji

**Comment by AleksandraDabrowska** [comment]
con_to_des -> design_format

**Comment by AleksandraDabrowska** [comment]
em_plot -> means_plot

**Comment by AleksandraDabrowska** [comment]
gene_loc -> gene_location

**Comment by AleksandraDabrowska** [comment]
sum_gen -> gene_stats

**Comment by AleksandraDabrowska** [comment]
dodatkowe funkcje: probes_location, islands_locations - w funkcji methylation_path

**Comment by AleksandraDabrowska** [comment]
genereg_vs_met -> methylation_path -> plot_methylation_path

**Comment by AleksandraDabrowska** [comment]
boxplot_that -> group_boxplot -> plot_diff_boxplot

**Comment by AleksandraDabrowska** [comment]
visual_volc -> visual_volcano -> plot_volcanoes

**Comment by AleksandraDabrowska** [comment]
visual_gene  i visual_volcano- zmiana kolejności argumentów condition.e, condition.m, data.e, data.m, gene, test.e, test.m

**Comment by agosiewska** [comment]
comparison table -> calculate_comparison_table
chromosome_data -> calculate_chromosome_data
data_stats -> calculate_data_stats
expr_nbinom -> test_nbinom - private
expr_nbinom2 -> test_nbinom2 - private

calculate_cpG_mean - private
calculate_data_stats - private

gene_location - private
gene_stats - private
islands_location - private

map_to_gene -> aggregate_probes
means_plot -> plot_means - private
pvalues_plot -> plot_pvalues - private
report_generate -> generate_report 
test_diff->calculate_test

**Comment by agosiewska** [comment]
Info w [NEWS](https://github.com/geneticsMiNIng/MLGenSig/blob/master/NEWS.md).
