### ISSUE TITLE
em_plot is not working

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/MLGenSig#85]
In the https://github.com/geneticsMiNIng/MLGenSig/blob/master/Vignette/Usage.Rmd
the `em_plot` function is used, but

```
> em_plot(BRCA_mRNAseq_chr17[,-1], condition, names=5)
Error: could not find function "em_plot"
```

**Comment by agosiewska** [comment]
Thanks, Usage is an old version of [Quick start](https://github.com/geneticsMiNIng/MLGenSig/blob/master/QuickStart/QuickStart.pdf) with old function names. I removed it.

**Comment by pbiecek** [comment]
There were examples for other interesting graphical functions like `p_values_plot` (and others)
Where I can find examples for them right now?

**Comment by agosiewska** [comment]
Right! 
I've added `plot_means()`, `plot_volcano()`, `plot_methylation_path()` and `plot_pvalue()` functions to the QuickStart.
