### ISSUE TITLE
plot_methylation_path is not working for > 2 groups

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/MLGenSig#88]
Example from the cheatsheet but for > than 2 groups

```
gr_met <-  BRCA_met$SUBTYPE
plot_methylation_path(BRCA_met, gr_met, gene="CACNA1G")
```

**Comment by agosiewska** [comment]
Now it's working for more than 2 groups
![image](https://user-images.githubusercontent.com/18423383/36162401-a9a9387a-10e6-11e8-9212-63a9beb79e98.png)
