### ISSUE TITLE
roxygen2 in dependencies/imports ?

### ISSUE THREAD

**Issue by MarcinKosinski** [geneticsMiNIng/MLGenSig#91]
You just use this package to build your package. You probably don't import any functionality from this package so that your package can work. This should be in the `Suggests` / `Enhances` but it also would be extraordinary. I suggest to completly remove this from the DESCRIPTION. You don't have import item in the NAMESPACE so I assume you don't use this pckg.

https://github.com/geneticsMiNIng/MLGenSig/blob/2b9adcb985185ebfce95a1191234fb146012285f/MLExpResso/DESCRIPTION#L30

cc @agosiewska @AleksandraDabrowska 

There is no `roxygen2` in dependencies of `dplyr` https://github.com/tidyverse/dplyr/blob/master/DESCRIPTION . One should rather have RoxygenNote.

Also there is no roxygen2 in the roxygen2 https://github.com/klutometis/roxygen/blob/master/DESCRIPTION

**Comment by agosiewska** [comment]
@MarcinKosinski  Thank you, I've removed it.
